=== PhiphiLeBoss12/PhiphiLeBoss12.github.io/Collection_AFCHAIN_Phileas/XML/musics.dtd
<!ENTITY % month "(1|2|3|4|5|6|7|8|9|10|11|12)">
<!ENTITY % day
                "(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)">
<!ENTITY % year "CDATA">

<!ENTITY % inline "img | keyword | a ">
<!ENTITY % datainline "(#PCDATA | %inline; )*">

<!ENTITY % coreattrs
    "id       ID      #IMPLIED
	 class    CDATA   #IMPLIED
	 title    CDATA   #IMPLIED"
>

<!ENTITY % URI "CDATA">
<!-- a Uniform Resource Identifier, see [RFC2396] -->

<!ENTITY % Length "CDATA">
<!-- nn for pixels or nn% for percentage length -->


<!ENTITY % Text "CDATA">



<!ELEMENT musicforwork (informations, album?, description, illustration?)>
<!ATTLIST musicforwork
    %coreattrs;
>


<!ELEMENT informations (title, artist+, duration?, release?, history)>
<!ATTLIST informations
    %coreattrs;
>

<!ELEMENT title %datainline;>
<!ATTLIST title
    %coreattrs;
>

<!ELEMENT artist %datainline;>
<!ATTLIST artist
    %coreattrs;
>

<!ELEMENT duration (#PCDATA)>
<!ATTLIST duration
    %coreattrs;
>

<!ELEMENT release EMPTY>
<!ATTLIST release
    %coreattrs;
    year    %year;  #REQUIRED
    month   %month; #IMPLIED
    day     %day;   #IMPLIED
>

<!ELEMENT history #PCDATA>
<!ATTLIST history
    %coreattrs;
>

<!ELEMENT album (illustration)?>
<!ATTLIST album
    %coreattrs;
    title       %Text;  #REQUIRED
    artist      %Text;  #REQUIRED
    yearrelease %year;  #IMPLIED
>


<!ELEMENT description (%datainline;, p)*>
<!ATTLIST description
    %coreattrs;
>


<!ELEMENT illustration (img)>
<!ATTLIST illustration
    %coreattrs;
>

<!ELEMENT img EMPTY>
<!ATTLIST img
    %coreattrs;
    src         %URI; #REQUIRED
    alt         %Text; #REQUIRED
    longdesc    %URI;          #IMPLIED
    height      %Length;       #IMPLIED
    width       %Length;       #IMPLIED
>

<!ELEMENT a (#PCDATA)*>
<!ATTLIST a
    %coreattrs;
    href        %URI;          #IMPLIED
>

<!ELEMENT p %datainline;>
<!ATTLIST p
    %coreattrs;
>

<!-- Some entities and elements have been inspired/copied by/from the example project from UPdago -->
<!-- Copied entites/elements : datainline, coreattr, uri, length, text a, img, p -->

=== PhiphiLeBoss12/PhiphiLeBoss12.github.io/XML/Paris_Texas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musicforwork SYSTEM "musics.dtd">
<musicforwork>
    <informations>
        <title> Paris, Texas </title>
        <artist> Gotan Project </artist>
        <duration> 6:45 </duration>
        <release year="2006"/>
        <history> Paris, Texas a été écrit et joué d'après un morceau écrit pour le film du meme nom. </history>
    </informations>

    <album title="lunatico" artist="Gotan Project" yearrelease="2006">
        <illustration>
            <img src="" alt=""/>
        </illustration>
    </album>

    <description>
        <p>
            Ce titre de Gotan project est idéal pour travailler
            grace à l'ambiance tranquille qui sort en l'écoutant.
            L'absence de paroles y est aussi appréciable.
        </p>
    </description>
</musicforwork>
